name: CI

on:
    pull_request: {}
    push: { branches: [main] }

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: oven-sh/setup-bun@v2
            - run: bun audit --audit-level=high

    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: oven-sh/setup-bun@v2
            - run: bun install --frozen-lockfile
            - run: bun run lint

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: oven-sh/setup-bun@v2
            - run: bun install --frozen-lockfile
            - run: bun run build
            - uses: actions/upload-pages-artifact@v5
              with:
                  path: dist

    deploy:
        if: github.ref == 'refs/heads/main'
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/deploy-pages@v5
              id: deployment
